[package]
name = "caching"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "caching"
path = "src/main.rs"

[dependencies]
parking_lot = { workspace = true }
dashmap = { workspace = true }
moka = { version = "0.12", features = ["sync"] }
rand = { workspace = true }
serde_json = { workspace = true }
